---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sada4py-deployment
spec:
  selector:
    matchLabels:
      app: sada4py
  replicas: 2
  template:
    metadata:
      labels:
        app: sada4py
    spec:
      containers:
      - name: sada4py
        image: moaikids/sada4py:1.1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 0.1
            memory: 32Mi
          requests:
            cpu: 0.1
            memory: 32Mi
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 3
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: sada4py-service
spec:
  selector:
    app: sada4py
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30000
                          


